services:
  mysql:
    image: mysql:8.0.36
    container_name: planhattan-mysql
    ports:
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # initialize database
    networks:
      - planhattan-network
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

networks:
  planhattan-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
    driver_opts:
      type: none
      device: ${PLANHATTAN_MYSQL_VOLUME}
      o: bind