services:

  planhattan-api:
    image: zeli8888/planhattan-api:${version}
    container_name: planhattan-api
    ports:
      - 8000:8000
    volumes:
      - planhattan-uploads:/home/planhattan-api/uploads/
    networks:
      - planhattan-network
    environment:
      - OPEN_WEATHER_KEY=${OPEN_WEATHER_KEY}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - PLANHATTAN_MYSQL_URL=jdbc:mysql://planhattan-mysql:3306/comp47360

networks:
  planhattan-network:
    driver: bridge

volumes:
  planhattan-uploads:
    driver: local
    driver_opts:
      type: none
      device: ${PLANHATTAN_UPLOADS}
      o: bind