services:

  planhattan-api:
    image: zeli8888/planhattan-api:1.0
    container_name: planhattan-api
    ports:
      - 443:443
    networks:
      - planhattan-network
    environment:
      - OPEN_WEATHER_KEY=${OPEN_WEATHER_KEY}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - PLANHATTAN_MYSQL_URL=jdbc:mysql://planhattan-mysql:3306/comp47360

networks:
  planhattan-network:
    driver: bridge